//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanBird.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palabras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Palabras()
        {
            this.Deletreo_Palabras = new HashSet<Deletreo_Palabras>();
            this.Repeticion_Letras = new HashSet<Repeticion_Letras>();
        }
    
        public int Codigo_Palabra { get; set; }
        public string Palabra { get; set; }
        public Nullable<int> Cantidad_Letras { get; set; }
        public Nullable<double> Indice_uso { get; set; }
        public string Palabra_Raiz { get; set; }
        public string Palabra_Limpia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deletreo_Palabras> Deletreo_Palabras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repeticion_Letras> Repeticion_Letras { get; set; }
    }
}
